### ISSUE TITLE
npx easy-oclif-cli $CODE_DIR ---> SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by paolodina** [YizYah/easy-oclif-cli#23] opened 2020-12-24 13:54 UTC
Hi, I'm trying the steps on readme but getting the following error.

I'm using node v12.5.0, any idea?

```
paolo@cmoth:~ $ cd /tmp/
paolo@cmoth:/tmp $ mkdir cli
paolo@cmoth:/tmp $ CODE_DIR=/tmp/cli/
paolo@cmoth:/tmp $ npx easy-oclif-cli $CODE_DIR
npx: installed 15 in 36.257s
Welcome to easy-oclif-cli! This process may a few minutes.  We will download a temporary version of ns-flip, and then of oclif.  You will have to enter some information at the prompts.
npx: installed 363 in 126.193s
/home/paolo/.npm/_npx/6143/lib/node_modules/easy-oclif-cli/template/general/init.ts:5
    init: async function(command: string, codeDir: string){
                                ^
SyntaxError: Unexpected token :
    at Module._compile (internal/modules/cjs/loader.js:760:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/paolo/.npm/_npx/6226/lib/node_modules/ns-flip/node_modules/ts-node/src/index.ts:851:44)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.createCodeBase (/home/paolo/.npm/_npx/6226/lib/node_modules/ns-flip/lib/codeGeneration/codeBases/createCodeBase.js:41:30)
    Error: problem generating code: SyntaxError: Unexpected token :
```

**Comment by YizYah** [comment] 2020-12-27 06:53
Hi!  Thanks for letting us know.

**Comment by YizYah** [comment] 2020-12-27 08:27
hi @paolodina can I ask what OS you have?  I'm having trouble reproducing the issue on ubuntu. I really don't think it's an issue with your node version.

**Comment by ghost** [comment] 2020-12-27 15:53
@YizYah What is your trouble on ubuntu?

**Comment by YizYah** [comment] 2020-12-27 16:10
I'm saying that it runs fine on ubuntu for me @bruth713.  I'm not sure what the problem is that he is experiencing.

**Comment by YizYah** [comment] 2020-12-27 16:35
@paolodina The problem has been reproduced by someone else with ubuntu. I'll have to get back to you tomorrow on this.
Thank you *very much* for reporting this! :smile:

**Comment by Venus713** [comment] 2020-12-27 18:08
I think it might be because of environment. In other words, maybe you forgot to mention that some packages should be installed globally.

**Comment by Venus713** [comment] 2020-12-27 19:00
@YizYah Would you check your globally installed npm packages?
I'd like to compare it with my things.

**Comment by paolodina** [comment] 2020-12-27 19:47
@YizYah hi, thanks for your reply. I'm on Debian 10.

Btw, if that matters:
```
$ npm list -g --depth=0
/home/paolo/.nvm/versions/node/v12.5.0/lib
├── @angular/cli@8.3.9
├── @quasar/cli@1.0.2
├── artillery@1.6.1
├── artillery-plugin-expect@1.3.0
├── eslint@6.7.1
├── groq-cli@0.2.1
├── hexo-cli@3.1.0
├── ndb@1.1.5
├── ng-tailwindcss@2.1.1
├── nodemon@1.19.4
├── npm@6.14.8
├── npm-check-updates@8.1.1
├── ts-node@8.4.1
├── typescript@3.6.3
└── yarn@1.22.4
```

If you need more info, please ask.

**Comment by YizYah** [comment] 2020-12-28 12:17
Just following up @paolodina there is a problem because typescript isn't properly being interpreted. 

The only functional workaround that I know at the moment is rather absurd:
1. clone easy-oclif-cli into a local directory $TEMPLATE
2. run npx ns-flip generate $CODE_DIR -t $TEMPLATE/src/template

The file that is creating a problem is $TEMPLATE/src/template/general/init.ts.  For some reason, that file is not being interpreted as a ts file unless it is in a directory that has been cloned rather than installed. We're continuing to work on this.

**Comment by YizYah** [comment] 2020-12-28 14:13
It seems the problem is, given that `easy-oclif-cl`i gets installed into the root node directory (of course), a ts file there is by default getting interpreted as a js file.  There's nothing wrong with the `easy-oclif-cli` files themselves--they can be copied to another directory and they work.

So one way that I think this could work is to modify the order of what happens in `ns-flip`.  Currently, the template directory is used for generating a code base (in this case the new cli), and then the directory gets copied over for future (re)generations.  But if first the template got copied over and then it was used, things might work better.

I've posted a question about this to StackOverflow: https://stackoverflow.com/questions/65478776/node-js-reading-ts-file-as-js-in-the-npm-root-directory.

**Comment by YizYah** [comment] 2020-12-28 16:25
https://github.com/NoStackApp/ns-flip/pull/97 is fixing this problem (issue #96 in `ns-flip`).  Currently in CI.  But also the template directory for `easy-oclif-cli` needed it's own `node_modules` directory for one of the packages used in `init`.

**Comment by YizYah** [comment] 2020-12-28 16:46
Oh, I forgot--the same problem that we were facing with ns-flip must be fixed as well for easy-oclif-cli--I changed it to ts from js today, but the bin won't run unless called with node directly.  So that is a separate issue but unfortunately it is delaying a fully functional release. See Issue #30.

**Comment by YizYah** [comment] 2020-12-29 07:48
@Venus713 I've released a version that seems to work.  Note that I do not have either `ns-flip` or `easy-oclif-cli` installed globally and yet this is working.  
```
~$ npm list -g --depth 0
/home/yisroel/.nvm/versions/node/v14.9.0/lib
+-- depcheck@1.2.0
+-- np@7.1.0
+-- npm@6.14.10
+-- npm-check-updates@9.1.2
+-- serverless@2.0.0
`-- yalc@1.0.0-pre.42
yisroel@yisroel-Spin-SP314-53N:~$ npx easy-oclif-cli $CODE_DIR
npx: installed 8 in 4.642s
Welcome to easy-oclif-cli! This process may a few minutes.  We will download a temporary version of ns-flip, and then of oclif.  You will have to enter some information at the prompts.
npx: installed 364 in 22.48s
  ✔ Execute Pre-Commands
  ✔ Add Meta-Data
  ✔ Install General Packages...
  ✔ Install Dev Packages...
  ✔ Check for baseApp
  ✔ Copy directory to new app directory
? enter value of packageName [string name of package]* boo3
? enter value of binName [string executable name if different than name] boo3
? enter value of author [string author of the package]* YizYah
? enter value of owner [string owner of the GitHub repo]* YizYah
? enter value of description [string one liner about what the cli does] test of 
npx version
? enter value of repositoryName [string repository on GitHub]* boo3
? enter value of license [string license] MIT
Generated the code at /home/yisroel/temp/junk/boo3.  For documentation: https://ns-flip.nostack.net/
Your template was created at /home/yisroel/temp/junk/boo3.

```
Can you please try and confirm?

**Comment by paolodina** [comment] 2020-12-29 08:57
@YizYah better but not still there for me.

Now the generation process starts (some dirs have been created), but stops along the way. Basically it "Cannot find module 'git-user-name'".

```
$ npx easy-oclif-cli $CODE_DIR
npx: installed 8 in 3.187s
Welcome to easy-oclif-cli! This process may a few minutes.  We will download a temporary version of ns-flip, and then of oclif.  You will have to enter some information at the prompts.
npx: installed 364 in 22.141s
Error: Cannot find module 'git-user-name'
Require stack:
- /home/paolo/tmp/manu/meta/template/general/init.ts
- /home/paolo/.npm/_npx/30742/lib/node_modules/ns-flip/lib/codeGeneration/codeBases/createCodeBase.js
- /home/paolo/.npm/_npx/30742/lib/node_modules/ns-flip/lib/commands/generate.js
- /home/paolo/.npm/_npx/30742/lib/node_modules/ns-flip/node_modules/@oclif/config/lib/plugin.js
- /home/paolo/.npm/_npx/30742/lib/node_modules/ns-flip/node_modules/@oclif/config/lib/config.js
- /home/paolo/.npm/_npx/30742/lib/node_modules/ns-flip/node_modules/@oclif/config/lib/index.js
- /home/paolo/.npm/_npx/30742/lib/node_modules/ns-flip/node_modules/@oclif/command/lib/command.js
- /home/paolo/.npm/_npx/30742/lib/node_modules/ns-flip/node_modules/@oclif/command/lib/index.js
- /home/paolo/.npm/_npx/30742/lib/node_modules/ns-flip/bin/run
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:892:15)
    at Function.Module._load (internal/modules/cjs/loader.js:742:27)
    at Module.require (internal/modules/cjs/loader.js:964:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/paolo/tmp/manu/meta/template/general/init.ts:1:21)
    at Module._compile (internal/modules/cjs/loader.js:1075:30)
    at Module.m._compile (/home/paolo/.npm/_npx/30742/lib/node_modules/ns-flip/node_modules/ts-node/src/index.ts:858:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1096:10)
    at Object.require.extensions.<computed> [as .ts] (/home/paolo/.npm/_npx/30742/lib/node_modules/ns-flip/node_modules/ts-node/src/index.ts:861:12)
    at Module.load (internal/modules/cjs/loader.js:940:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/paolo/tmp/manu/meta/template/general/init.ts',
    '/home/paolo/.npm/_npx/30742/lib/node_modules/ns-flip/lib/codeGeneration/codeBases/createCodeBase.js',
    '/home/paolo/.npm/_npx/30742/lib/node_modules/ns-flip/lib/commands/generate.js',
    '/home/paolo/.npm/_npx/30742/lib/node_modules/ns-flip/node_modules/@oclif/config/lib/plugin.js',
    '/home/paolo/.npm/_npx/30742/lib/node_modules/ns-flip/node_modules/@oclif/config/lib/config.js',
    '/home/paolo/.npm/_npx/30742/lib/node_modules/ns-flip/node_modules/@oclif/config/lib/index.js',
    '/home/paolo/.npm/_npx/30742/lib/node_modules/ns-flip/node_modules/@oclif/command/lib/command.js',
    '/home/paolo/.npm/_npx/30742/lib/node_modules/ns-flip/node_modules/@oclif/command/lib/index.js',
    '/home/paolo/.npm/_npx/30742/lib/node_modules/ns-flip/bin/run'
  ]
}
    Error: problem generating code: Error: Cannot find module 'git-user-name'
    Require stack:
    - /home/paolo/tmp/manu/meta/template/general/init.ts
    - /home/paolo/.npm/_npx/30742/lib/node_modules/ns-flip/lib/codeGeneration/codeBases/createCodeBase.js
    - /home/paolo/.npm/_npx/30742/lib/node_modules/ns-flip/lib/commands/generate.js
    - /home/paolo/.npm/_npx/30742/lib/node_modules/ns-flip/node_modules/@oclif/config/lib/plugin.js
    - /home/paolo/.npm/_npx/30742/lib/node_modules/ns-flip/node_modules/@oclif/config/lib/config.js
    - /home/paolo/.npm/_npx/30742/lib/node_modules/ns-flip/node_modules/@oclif/config/lib/index.js
    - /home/paolo/.npm/_npx/30742/lib/node_modules/ns-flip/node_modules/@oclif/command/lib/command.js
    - /home/paolo/.npm/_npx/30742/lib/node_modules/ns-flip/node_modules/@oclif/command/lib/index.js
    - /home/paolo/.npm/_npx/30742/lib/node_modules/ns-flip/bin/run
```

**Comment by YizYah** [comment] 2020-12-29 09:29
Noted @paolodina.

**Comment by YizYah** [comment] 2020-12-29 12:04
@paolodina & @Venus713
I've ended up creating [another issue](https://github.com/NoStackApp/ns-flip/issues/98) on `ns-flip` and resolving it.  It should work now for everyone.  Could someone please confirm that this is now fixed?  Here's about what your session should look like:
```
yisroel@yisroel-Spin-SP314-53N:~$ CODE_DIR=~/temp/junk/foo
yisroel@yisroel-Spin-SP314-53N:~$ npx easy-oclif-cli $CODE_DIR
npx: installed 8 in 1.718s
Welcome to easy-oclif-cli! This process may a few minutes.  We will download a temporary version of ns-flip, which will install   needed packages. You will have to enter some information at the prompts.
npx: installed 364 in 43.583s
  ✔ Execute Pre-Commands
  ✔ Add Meta-Data
  ✔ Install General Packages...
  ✔ Install Dev Packages...
  ✔ Check for baseApp
  ✔ Copy directory to new app directory
? enter value of packageName [string name of package]* foo
? enter value of binName [string executable name if different than name] foo
? enter value of author [string author of the package]* YizYah
? enter value of owner [string owner of the GitHub repo]* YizYah
? enter value of description [string one liner about what the cli does] 
? enter value of repositoryName [string repository on GitHub]* foo
? enter value of license [string license] MIT
Generated the code at /home/yisroel/temp/junk/foo.  For documentation: https://ns-flip.nostack.net/
Your template was created at /home/yisroel/temp/junk/foo.
```

**Comment by paolodina** [comment] 2020-12-29 12:34
Awesome, thank you very much it works now. :+1: 

For me this issue can be closed. Close it if you want.

**Comment by Venus713** [comment] 2020-12-29 12:35
Great, It's resolved finally. :+1: :100:

**Comment by YizYah** [comment] 2020-12-29 12:39
@paolodina you are just awesome.  I cannot thank you enough for bringing this to our attention.  I'll bet there were others who tried it and didn't tell us.  I think that most people aren't that proactive :smiley: 

Please let me know if there's ever anything I can do for you!

**Closed as completed** 2020-12-29 12:39 UTC
Labels: bug
